.github/workflows/sandbox-build-deploy.yml, packages/worksheet/package.json, scripts/pack-prod-build.sh
github workfkow script which builds and deploys modules and host app on sandbox
=> feat: CICD - github action to deploy on sandbox

packages/attendance/src/App.js, packages/attendance/src/pages/Attendance.js, packages/attendance/src/pages/reports/CompareReport.js, packages/attendance/src/pages/reports/Report.js, packages/attendance/src/pages/reports/ReportDetail.js, packages/attendance/src/pages/sms/MessageHistory.js, packages/attendance/src/pages/sms/SendSMS.js, packages/classes/src/pages/ClassDetails.js, packages/common-lib/src/components/AppShell.tsx, packages/student/src/App.js, packages/student/src/pages/students/Student.js, packages/student/src/pages/students/StudentDetails.js, packages/teacher-app/src/App.js, packages/teacher-app/src/pages/Home.js, packages/teacher-app/src/pages/MyClasses.js, packages/worksheet/src/pages/QuestionBank.js
=> fix: #55 Hide Footer link

.github/workflows/sandbox-build-deploy.yml
=> fix: CICD - env  and branch name change for sandbox deployment

packages/common-lib/src/components/AppShell.tsx
=> fix: #58  - Common-lib build is failing

packages/attendance/src/components/AttendanceComponent.js, packages/attendance/src/pages/Attendance.js, packages/attendance/src/services/attendanceServiceRegistry.js, packages/classes/src/services/teacherServiceRegistry.js, packages/common-lib/src/components/IconByName.js, packages/core/src/services/teacherServiceRegistry.js, packages/profile/src/services/teacherServiceRegistry.js, packages/student/src/components/students/Card.js, packages/student/src/components/students/StudentEdit.js
conflicts solved.
- Attendance bug.
- See full report button.
=> conflicts solved

packages/classes/src/pages/MyClassRoute/Molecules/ChooseClassActionSheet.js, packages/core/src/pages/Login.js
=> fix: class list issue

packages/teacher-app/public/index.html
For SEO, the meta description tag in the teacher-app micro frontend was changed from => 
"Web site created using create-react-app" 
**to** 
"The teacher app Micro Frontend used in the Shiksha app.
It can also function as a standalone package."
In the index.html file of the public folder of teacher-app, changed the meta description tag.
The app may be run individually or as whole. And then the meta tag may be inspected using the developer tools in any browser of choice.
=> Fixed the meta description tag in the teacher app micro frontend

.github/workflows/sandbox-build-deploy.yml
Github action build and deploy error fix
=> fix: github action build and deploy error fix

packages/attendance/src/components/AttendanceComponent.js, packages/attendance/src/pages/Attendance.js, packages/common-lib/src/components/calender.js, packages/common-lib/src/index.tsx, packages/common-lib/src/services/configApiRegistryService.js
admin some config and mark attendance optimization
- integrate config Api at attendance module
- resolve mark attendance slowness
=> admin config and mark attendance optimization

.gitignore
problem: with each PR, that is done after some unsuccessfull yarn command, an un-necessary file yarn-error.log gets included in the pull request.
yarn-error.log is auto created file, and is specific to each developer ( just like node_modules ) So, changes made there should not disturb the pull requests and merges on github/git.
added yarn-error.log to .gitignore
=> update gitignore: add yarn-error.log

packages/attendance/src/components/AttendanceComponent.js, packages/common-lib/src/components/HeightWidth.js, packages/common-lib/src/components/layout/Footer.js, packages/common-lib/src/components/layout/Layout.js, packages/teacher-app/src/pages/Home.js, packages/worksheet/src/pages/CreateWorksheet.js
Drawer Position
1. Fixing drawers 
2. changes in layout
3. update footer
=> Drawer Position

packages/attendance/public/index.html, packages/calendar/public/index.html, packages/classes/public/index.html, packages/core/public/index.html, packages/notification/public/index.html, packages/profile/public/index.html, packages/student/public/index.html, packages/teacher-app/public/index.html, packages/worksheet/public/index.html
As per the requirement, meta description tags for each of the modules have been added.
Edited the index.html file in the public folder for each module.
We can inspect by using the developer tools in any browser of choice.
=> Edited the meta tags in all modules

module-template/public/index.html, packages/attendance/public/index.html, packages/calendar/public/index.html, packages/classes/public/index.html, packages/core/public/index.html, packages/notification/public/index.html, packages/profile/public/index.html, packages/student/public/index.html, packages/teacher-app/public/index.html, packages/worksheet/public/index.html
As required, the title tags of all index.html file have been changed to improve the overall appearance of the app.
Updated the title tag in all index.html files (for all packages)
=> Changed the titles in index.html file

packages/attendance/src/components/AttendanceComponent.js, packages/attendance/src/pages/sms/SendSMS.js, packages/student/src/components/students/Card.js
=> fix: static holiday and api config

packages/attendance/src/components/AttendanceComponent.js, packages/attendance/src/pages/reports/Report.js, packages/common-lib/src/services/attendanceRegistryService.js
Attendance config API
- Report Config Api
- Attendance config API
=> Attendance config API

packages/assessment/public/firebase-messaging-sw.js, packages/assessment/src/App.js, packages/attendance/public/firebase-messaging-sw.js, packages/attendance/src/App.js, packages/calendar/public/firebase-messaging-sw.js, packages/calendar/src/App.js, packages/classes/public/firebase-messaging-sw.js, packages/classes/src/App.js, packages/common-lib/src/components/firebase/firebase.js, packages/notification/public/firebase-messaging-sw.js, packages/notification/src/App.js, packages/profile/public/firebase-messaging-sw.js, packages/profile/src/App.js, packages/student/public/firebase-messaging-sw.js, packages/student/src/App.js, packages/worksheet/public/firebase-messaging-sw.js, packages/worksheet/src/App.js
1. DOMException Service Registration Error Fix
2. Service worker added to all the modules (firebase-messaging-sw.js + App.js changes)
3. firebaseConfig and publicKey changed from demoParesh to Shiksha
=> In app notification

packages/common-lib/src/services/commentRegistryService.js, packages/common-lib/src/services/questionRegistryService.js, packages/common-lib/src/services/teacherRegistryService.js, packages/common-lib/src/services/worksheetRegistryService.js, packages/worksheet/src/components/Actionsheet/CommentActionsheet.js, packages/worksheet/src/components/CreateWorksheet/AddDescriptionPage.js, packages/worksheet/src/components/QuestionBox/index.js
worksheet and question changes
- worksheet
- question
=> worksheet and question

packages/common-lib/src/index.tsx, packages/common-lib/src/services/commentRegistryService.js, packages/common-lib/src/services/userRegistryService.js, packages/core/src/pages/Login.js, packages/notification/src/pages/Notification.js, packages/profile/src/components/TeacherEdit.js, packages/profile/src/pages/AttendanceReport.js, packages/profile/src/pages/Profile.js, packages/student/src/components/students/StudentEdit.js, packages/teacher-app/src/App.js, packages/worksheet/src/components/Actionsheet/CommentActionsheet.js, packages/worksheet/src/components/WorksheetBox/index.js, packages/worksheet/src/pages/WorksheetQuestionBank.js
Change API end point Teacher to User
- Change teacherRegistryService to userRegistryService
=> Change API end point Teacher to User

packages/teacher-app/src/App.js, scripts/oauth2-proxy-nginx.conf.template, scripts/oauth2-proxy-service-setup.md, scripts/oauth2-proxy.cfg, scripts/oauth2-proxy.service.template
Enable auth proxy - fix issue of token passing in dev environment
add auth proxy setup configuration template files
=> fix: enable oauth proxy 

packages/attendance/public/locales/en/attendance.json, packages/attendance/public/locales/hi/attendance.json, packages/attendance/src/pages/Attendance.js, packages/attendance/src/pages/reports/Report.js, packages/common-lib/src/components/IconByName.js, packages/common-lib/src/components/SearchLayout.js, packages/common-lib/src/components/helper.js, packages/teacher-app/public/locales/en/translation.json, packages/teacher-app/public/locales/hi/translation.json, packages/teacher-app/src/pages/TeacherHome.js, packages/worksheet/src/components/CreateWorksheet/AddDescriptionPage.js, packages/worksheet/src/pages/Worksheet.js, packages/worksheet/src/pages/WorksheetShare.js
Bug slowing of text changes and UI changes.
- Attendance 
- Self attendance
- Worksheet
=> Bugs slowing

.github/workflows/prod-build-deploy.yml
github workdflow file added to deploy to prod env
=> prod deployment workflow

.github/workflows/prod-build-deploy.yml
=> fix: prod deployment workflow name

.github/workflows/prod-build-deploy.yml
* fix: prod build deploy github added
* fix: prod build deploy github added
* workflow name corrected
Co-authored-by: Arun Rajput <arunrajput@Aruns-MacBook-Pro-2.local>
=> fix: prod deployment workflow name (#293)

packages/common-lib/src/hooks/useAuthFlow.js, packages/common-lib/src/services/classRegistryService.js, packages/common-lib/src/services/mentorRegisteryService.js, packages/schools/src/components/SchoolAcademicDetailCard.js, packages/schools/src/components/SchoolAdminDetailCard.js, packages/schools/src/components/SchoolAdminTile.js, packages/schools/src/components/TeacherListCard.js
Parent class wise student count at school profile.
=> Parent class wise student count at school profile.

packages/assessment/.env.development, packages/assessment/.env.production, packages/assessment/src/assets/constants.js, packages/assessment/src/pages/QumlTest.js
Parent Url for QUML player
- QUMLTest.js
=> Parent Url for QUML player
